

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PyUI3"
authors = [{name = "Johnny Konczal", email = "johndrostan@outlook.com"}]
dynamic = ["version", "description"]
readme = "README.md"
dependencies = [
    "win32more",
    "tk"

]

